---
- hosts: web
  become: true
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: Iniciar el servicio de Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Copiar el archivo holamundo.html
      copy:
        src: ./holamundo.html
        dest: /var/www/html/index.html
